In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/sukitharathnayake/CodeRepo/ST4035/Data/Earthquake Database ST 4035.csv')

In [3]:
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [5]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
magnitude,1000.0,6.940150,0.438148,6.5000,6.60000,6.8000,7.10000,9.1000
cdi,1000.0,3.605000,3.328972,0.0000,0.00000,4.0000,7.00000,9.0000
mmi,1000.0,6.027000,1.433990,1.0000,5.00000,6.0000,7.00000,10.0000
tsunami,1000.0,0.325000,0.468609,0.0000,0.00000,0.0000,1.00000,1.0000
sig,1000.0,847.915000,301.802632,650.0000,691.00000,744.0000,874.25000,2910.0000
nst,1000.0,193.918000,239.045858,0.0000,0.00000,0.0000,403.00000,934.0000
dmin,1000.0,1.125174,2.073164,0.0000,0.00000,0.0000,1.54925,17.6540
gap,1000.0,20.926290,24.415895,0.0000,0.00000,18.0000,27.00000,239.0000
depth,1000.0,74.612541,130.812590,2.7000,16.00000,29.0000,55.00000,670.8100
latitude,1000.0,4.315554,26.633320,-61.8484,-13.51850,-2.4435,25.16725,71.6312
longitude,1000.0,51.486576,117.478302,-179.9680,-71.69445,107.7910,148.36475,179.6620

## a)

19 columns and 1000 rows

In [6]:
#2
df.drop(columns=['date_time', 'location'], inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   cdi        1000 non-null   int64
 3   mmi        1000 non-null   int64
 4   alert      449 non-null    object
 5   tsunami    1000 non-null   int64
 6   sig        1000 non-null   int64
 7   net        1000 non-null   object
 8   nst        1000 non-null   int64
 9   dmin       1000 non-null   float64
 10  gap        1000 non-null   float64
 11  magType    1000 non-null   object
 12  depth      1000 non-null   float64
 13  latitude   1000 non-null   float64
 14  longitude  1000 non-null   float64
 15  continent  284 non-null    object
 16  country    651 non-null    object
dtypes: float64(6), int64(5), object(6)
memory usage: 132.9+ KB

## c)

There are missing values in continent and country

In [8]:
df[['continent', 'country', 'alert']] = df[['continent', 'country', 'alert']].ffill()

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   cdi        1000 non-null   int64
 3   mmi        1000 non-null   int64
 4   alert      1000 non-null   object
 5   tsunami    1000 non-null   int64
 6   sig        1000 non-null   int64
 7   net        1000 non-null   object
 8   nst        1000 non-null   int64
 9   dmin       1000 non-null   float64
 10  gap        1000 non-null   float64
 11  magType    1000 non-null   object
 12  depth      1000 non-null   float64
 13  latitude   1000 non-null   float64
 14  longitude  1000 non-null   float64
 15  continent  998 non-null    object
 16  country    1000 non-null   object
dtypes: float64(6), int64(5), object(6)
memory usage: 132.9+ KB

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   cdi        1000 non-null   int64
 3   mmi        1000 non-null   int64
 4   alert      1000 non-null   object
 5   tsunami    1000 non-null   int64
 6   sig        1000 non-null   int64
 7   net        1000 non-null   object
 8   nst        1000 non-null   int64
 9   dmin       1000 non-null   float64
 10  gap        1000 non-null   float64
 11  magType    1000 non-null   object
 12  depth      1000 non-null   float64
 13  latitude   1000 non-null   float64
 14  longitude  1000 non-null   float64
 15  continent  998 non-null    object
 16  country    1000 non-null   object
dtypes: float64(6), int64(5), object(6)
memory usage: 132.9+ KB

In [11]:
#d)
Q1 = df['magnitude'].quantile(0.25)
Q3 = df['magnitude'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df['magnitude'] >= lower_bound) & (df['magnitude'] <= upper_bound)]

In [12]:
#e)

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['alert'] = le.fit_transform(df['alert'])

In [14]:
df['alert']

0      0
1      3
2      0
3      0
4      0
      ..
995    2
996    2
997    2
998    2
999    2
Name: alert, Length: 953, dtype: int64

In [15]:
df['alert'].unique()

array([0, 3, 1, 2])

In [16]:
import pandas as pd

url = 'https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv'
df = pd.read_csv(url)
print(df.head())

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

In [17]:
messy_data = pd.DataFrame({
    'student_id':  [1, 2, 2, 3, 4, 5, 6, None],
    'Name':        ['Alice', 'bob', 'bob', 'CHARLIE', 'Diana', 'eve', 'Frank', None],
    'Age':         ['21', '22', '22', 'nineteen', '20', '23', None, '25'],
    'Score':       [85, 90, 90, 78, None, 88, 72, 95],
    'Department':  ['CS', 'cs', 'cs', 'Math', 'MATH', 'Physics', 'physics', 'CS'],
    'enroll_date': ['2023-09-01', '2023/09/01', '2023/09/01',
                    '01-09-2023', '2023-09-01', 'Sep 1 2023',
                    '2023-09-01', '2023-09-01']
})

messy_data.to_csv("student_survey.csv", index=False)

# Read it back
raw_survey = pd.read_csv("student_survey.csv")

In [18]:
# Dimensions
raw_survey.shape           

# Column names and types
raw_survey.info()

# First/last rows
raw_survey.head(5)
raw_survey.tail(5)

# Statistical summary
raw_survey.describe(include='all')

# Count missing values per column
raw_survey.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   7 non-null      float64
 1   Name         7 non-null      object
 2   Age          7 non-null      object
 3   Score        7 non-null      float64
 4   Department   8 non-null      object
 5   enroll_date  8 non-null      object
dtypes: float64(2), object(4)
memory usage: 516.0+ bytes

student_id     1
Name           1
Age            1
Score          1
Department     0
enroll_date    0
dtype: int64

In [19]:
# Check for duplicates
raw_survey.duplicated().sum()

# Remove duplicates
survey = raw_survey.drop_duplicates().reset_index(drop=True)

In [20]:
# Remove rows where student_id is missing
survey = survey.dropna(subset=['student_id'])

# Impute numeric missing with the median
survey['Score'] = survey['Score'].fillna(survey['Score'].median())

# Impute character missing with "Unknown"
survey['Name'] = survey['Name'].fillna('Unknown')

In [21]:
# Single condition
#df[df['continent'] == 'Asia']

# Multiple conditions (AND)
df[(df['continent'] == 'Asia') & (df['year'] >= 2000)]

# OR condition
#df[(df['country'] == 'India') | (df['country'] == 'China')]

# Filter using isin()
#df[df['country'].isin(['India', 'China', 'Japan'])]

                 country  year          pop continent  lifeExp     gdpPercap
10           Afghanistan  2002   25268405.0      Asia   42.129    726.734055
11           Afghanistan  2007   31889923.0      Asia   43.828    974.580338
94               Bahrain  2002     656397.0      Asia   74.795  23403.559270
95               Bahrain  2007     708573.0      Asia   75.635  29796.048340
106           Bangladesh  2002  135656790.0      Asia   62.013   1136.390430
...                  ...   ...          ...       ...      ...           ...
1655             Vietnam  2007   85262356.0      Asia   74.249   2441.576404
1666  West Bank and Gaza  2002    3389578.0      Asia   72.370   4515.487575
1667  West Bank and Gaza  2007    4018332.0      Asia   73.422   3025.349798
1678          Yemen Rep.  2002   18701257.0      Asia   60.308   2234.820827
1679          Yemen Rep.  2007   22211743.0      Asia   62.698   2280.769906

[66 rows x 6 columns]

In [22]:
countries = pd.DataFrame({
    'country': ['India', 'China', 'Brazil', 'Germany'],
    'region':  ['South Asia', 'East Asia', 'Latin America', 'Europe']
})

scores = pd.DataFrame({
    'country': ['India', 'China', 'Brazil', 'Japan'],
    'hdi':     [0.633, 0.761, 0.754, 0.925]
})

In [23]:
print(pd.merge(countries, scores, on='country', how='inner'))

  country         region    hdi
0   India     South Asia  0.633
1   China      East Asia  0.761
2  Brazil  Latin America  0.754

In [24]:
print(pd.merge(countries, scores, on='country', how='outer'))

   country         region    hdi
0   Brazil  Latin America  0.754
1    China      East Asia  0.761
2  Germany         Europe    NaN
3    India     South Asia  0.633
4    Japan            NaN  0.925

In [25]:
print(pd.merge(countries, scores, on='country', how='left'))

   country         region    hdi
0    India     South Asia  0.633
1    China      East Asia  0.761
2   Brazil  Latin America  0.754
3  Germany         Europe    NaN

In [26]:
print(pd.merge(countries, scores, on='country', how='right'))

  country         region    hdi
0   India     South Asia  0.633
1   China      East Asia  0.761
2  Brazil  Latin America  0.754
3   Japan            NaN  0.925

In [27]:
df.agg({
    'lifeExp':   'mean',
    'gdpPercap': 'median',
    'country':   'nunique'
})

lifeExp        59.474439
gdpPercap    3531.846988
country       142.000000
dtype: float64

In [28]:
(
    df
    .groupby(['continent', 'year'])
    .agg(
        avg_lifeExp = ('lifeExp',   'mean'),
        avg_gdp     = ('gdpPercap', 'mean'),
        n           = ('country',   'count')
    )
    .reset_index()
)

   continent  year  avg_lifeExp       avg_gdp   n
0     Africa  1952    39.135500   1252.572466  52
1     Africa  1957    41.266346   1385.236062  52
2     Africa  1962    43.319442   1598.078825  52
3     Africa  1967    45.334538   2050.363801  52
4     Africa  1972    47.450942   2339.615674  52
5     Africa  1977    49.580423   2585.938508  52
6     Africa  1982    51.592865   2481.592960  52
7     Africa  1987    53.344788   2282.668991  52
8     Africa  1992    53.629577   2281.810333  52
9     Africa  1997    53.598269   2378.759555  52
10    Africa  2002    53.325231   2599.385159  52
11    Africa  2007    54.806038   3089.032605  52
12  Americas  1952    53.279840   4079.062552  25
13  Americas  1957    55.960280   4616.043733  25
14  Americas  1962    58.398760   4901.541870  25
15  Americas  1967    60.410920   5668.253496  25
16  Americas  1972    62.394920   6491.334139  25
17  Americas  1977    64.391560   7352.007126  25
18  Americas  1982    66.228840   7506.737088  25
19  Americas  1987    68.090720   7793.400261  25
20  Americas  1992    69.568360   8044.934406  25
21  Americas  1997    71.150480   8889.300863  25
22  Americas  2002    72.422040   9287.677107  25
23  Americas  2007    73.608120  11003.031625  25
24      Asia  1952    46.314394   5195.484004  33
25      Asia  1957    49.318544   5787.732940  33
26      Asia  1962    51.563223   5729.369625  33
27      Asia  1967    54.663640   5971.173374  33
28      Asia  1972    57.319269   8187.468699  33
29      Asia  1977    59.610556   7791.314020  33
30      Asia  1982    62.617939   7434.135157  33
31      Asia  1987    64.851182   7608.226508  33
32      Asia  1992    66.537212   8639.690248  33
33      Asia  1997    68.020515   9834.093295  33
34      Asia  2002    69.233879  10174.090397  33
35      Asia  2007    70.728485  12473.026870  33
36    Europe  1952    64.408500   5661.057435  30
37    Europe  1957    66.703067   6963.012816  30
38    Europe  1962    68.539233   8365.486814  30
39    Europe  1967    69.737600  10143.823757  30
40    Europe  1972    70.775033  12479.575246  30
41    Europe  1977    71.937767  14283.979110  30
42    Europe  1982    72.806400  15617.896551  30
43    Europe  1987    73.642167  17214.310727  30
44    Europe  1992    74.440100  17061.568084  30
45    Europe  1997    75.505167  19076.781802  30
46    Europe  2002    76.700600  21711.732422  30
47    Europe  2007    77.648600  25054.481636  30
48   Oceania  1952    69.255000  10298.085650   2
49   Oceania  1957    70.295000  11598.522455   2
50   Oceania  1962    71.085000  12696.452430   2
51   Oceania  1967    71.310000  14495.021790   2
52   Oceania  1972    71.910000  16417.333380   2
53   Oceania  1977    72.855000  17283.957605   2
54   Oceania  1982    74.290000  18554.709840   2
55   Oceania  1987    75.320000  20448.040160   2
56   Oceania  1992    76.945000  20894.045885   2
57   Oceania  1997    78.190000  24024.175170   2
58   Oceania  2002    79.740000  26938.778040   2
59   Oceania  2007    80.719500  29810.188275   2

In [29]:
(
    df.groupby('country')['lifeExp']
    .mean()
    .reset_index(name='avg_life')
    .sort_values('avg_life', ascending=False)
    .head(10)
)

         country   avg_life
57       Iceland  76.511417
122       Sweden  76.177000
95        Norway  75.843000
90   Netherlands  75.648500
123  Switzerland  75.565083
20        Canada  74.902750
66         Japan  74.826917
5      Australia  74.662917
34       Denmark  74.370167
44        France  74.348917

In [30]:
df['rank_in_continent'] = (
    df.groupby(['continent', 'year'])['lifeExp']
    .rank(ascending=False, method='min')
)
df[df['rank_in_continent'] == 1]

,country,year,pop,continent,lifeExp,gdpPercap,rank_in_continent
61,Australia,1957,9712569.0,Oceania,70.330,10949.649590,1.0
64,Australia,1972,13177000.0,Oceania,71.930,16788.629480,1.0
65,Australia,1977,14074100.0,Oceania,73.490,18334.197510,1.0
66,Australia,1982,15184200.0,Oceania,74.740,19477.009280,1.0
67,Australia,1987,16257249.0,Oceania,76.320,21888.889030,1.0
68,Australia,1992,17481977.0,Oceania,77.560,23424.766830,1.0
69,Australia,1997,18565243.0,Oceania,78.830,26997.936570,1.0
70,Australia,2002,19546792.0,Oceania,80.370,30687.754730,1.0
71,Australia,2007,20434176.0,Oceania,81.235,34435.367440,1.0
240,Canada,1952,14785584.0,Americas,68.750,11367.161120,1.0
241,Canada,1957,17010154.0,Americas,69.960,12489.950060,1.0
242,Canada,1962,18985849.0,Americas,71.300,13462.485550,1.0
243,Canada,1967,20819767.0,Americas,72.130,16076.588030,1.0
244,Canada,1972,22284500.0,Americas,72.880,18970.570860,1.0
245,Canada,1977,23796400.0,Americas,74.210,22090.883060,1.0
246,Canada,1982,25201900.0,Americas,75.760,22898.792140,1.0
247,Canada,1987,26549700.0,Americas,76.860,26626.515030,1.0
248,Canada,1992,28523502.0,Americas,77.950,26342.884260,1.0
249,Canada,1997,30305843.0,Americas,78.610,28954.925890,1.0
250,Canada,2002,31902268.0,Americas,79.770,33328.965070,1.0
251,Canada,2007,33390141.0,Americas,80.653,36319.235010,1.0
685,Iceland,1957,165110.0,Europe,73.470,9244.001412,1.0
686,Iceland,1962,182053.0,Europe,73.680,10350.159060,1.0
689,Iceland,1977,221823.0,Europe,76.110,19654.962470,1.0
690,Iceland,1982,233997.0,Europe,76.990,23269.607500,1.0
692,Iceland,1992,259012.0,Europe,78.770,25144.392010,1.0
695,Iceland,2007,301931.0,Europe,81.757,36180.789190,1.0
756,Israel,1952,1620914.0,Asia,65.390,4086.522128,1.0
757,Israel,1957,1944401.0,Asia,67.840,5385.278451,1.0
758,Israel,1962,2310904.0,Asia,69.390,7105.630706,1.0
795,Japan,1967,100825279.0,Asia,71.430,9847.788607,1.0
796,Japan,1972,107188273.0,Asia,73.420,14778.786360,1.0
797,Japan,1977,113872473.0,Asia,75.380,16610.377010,1.0
798,Japan,1982,118454974.0,Asia,77.110,19384.105710,1.0
799,Japan,1987,122091325.0,Asia,78.670,22375.941890,1.0
800,Japan,1992,124329269.0,Asia,79.360,26824.895110,1.0
801,Japan,1997,125956499.0,Asia,80.690,28816.584990,1.0
802,Japan,2002,127065841.0,Asia,82.000,28604.591900,1.0
803,Japan,2007,127467972.0,Asia,82.603,31656.068060,1.0
973,Mauritius,1957,609816.0,Africa,58.089,2034.037981,1.0
974,Mauritius,1962,701016.0,Africa,60.246,2529.067487,1.0
975,Mauritius,1967,789309.0,Africa,61.557,2475.387562,1.0
1092,New Zealand,1952,1994794.0,Oceania,69.390,10556.575660,1.0
1094,New Zealand,1962,2488550.0,Oceania,71.240,13175.678000,1.0
1095,New Zealand,1967,2728150.0,Oceania,71.520,14463.918930,1.0
1140,Norway,1952,3327728.0,Europe,72.670,10095.421720,1.0
1260,Reunion,1952,257700.0,Africa,52.724,2718.885295,1.0
1264,Reunion,1972,461633.0,Africa,64.274,5047.658563,1.0
1265,Reunion,1977,492095.0,Africa,67.064,4319.804067,1.0
1266,Reunion,1982,517810.0,Africa,69.885,5267.219353,1.0
1267,Reunion,1987,562035.0,Africa,71.913,5303.377488,1.0
1268,Reunion,1992,622191.0,Africa,73.615,6101.255823,1.0
1269,Reunion,1997,684810.0,Africa,74.772,6071.941411,1.0
1270,Reunion,2002,743981.0,Africa,75.744,6316.165200,1.0
1271,Reunion,2007,798094.0,Africa,76.442,7670.122558,1.0
1467,Sweden,1967,7867931.0,Europe,74.160,15258.296970,1.0
1468,Sweden,1972,8122293.0,Europe,74.720,17832.024640,1.0
1473,Sweden,1997,8897619.0,Europe,79.390,25266.594990,1.0
1483,Switzerland,1987,6649942.0,Europe,77.410,30281.704590,1.0
1486,Switzerland,2002,7361757.0,Europe,80.620,34480.957710,1.0

In [31]:
import pandas as pd

url = 'https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv'
df = pd.read_csv(url)
print(df.head())

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

In [32]:
df_07 = df[df['year'] == 2007]
df_07.head()

        country  year         pop continent  lifeExp     gdpPercap
11  Afghanistan  2007  31889923.0      Asia   43.828    974.580338
23      Albania  2007   3600523.0    Europe   76.423   5937.029526
35      Algeria  2007  33333216.0    Africa   72.301   6223.367465
47       Angola  2007  12420476.0    Africa   42.731   4797.231267
59    Argentina  2007  40301927.0  Americas   75.320  12779.379640

In [33]:
(
    df_07
    .groupby(['continent'])
    .agg(
        avg_lifeExp = ('lifeExp',   'mean'),
        avg_gdp     = ('gdpPercap', 'mean')
    )
    .reset_index()
)

  continent  avg_lifeExp       avg_gdp
0    Africa    54.806038   3089.032605
1  Americas    73.608120  11003.031625
2      Asia    70.728485  12473.026870
3    Europe    77.648600  25054.481636
4   Oceania    80.719500  29810.188275

Oceania has the higest average gpd while Africa has the lowest average life expectency

In [34]:
df['gdp_billion'] = (df['gdpPercap'] * df['pop']) / 1e9

df['decade'] = (df['year'] // 10 * 10).astype(str) + 's'

top_5_2007 = df[df['year'] == 2007].nlargest(5, 'gdp_billion')

print(top_5_2007[['country', 'gdp_billion']])

            country   gdp_billion
1619  United States  12934.458535
299           China   6539.500929
803           Japan   4035.134797
707           India   2722.925439
575         Germany   2650.870894

# Web Scarapping